version: '3'
services:
  vpronginx: 
    image: dineshtamang14/vprofile-web:v1
    ports:
      - "80:80"

  vproapp:
    image: dineshtamang14/vprofile-app:v1
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vprocache01:
    image: memcached
    ports: 
      - "11211:11211"
    
  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest 

  vprodb:
    image: dineshtamang14/vprofile-db:v1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass 

volumes:
    vprodbdata: {}
    vproappdata: {}